# Generated by Django 4.0.4 on 2022-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_department_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='840.212.9490', max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(default='Wall voice actually drive pull detail onto. Friend first school security price firm. Skill fall already player street level.', max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='main/photos', verbose_name='Photo'),
        ),
    ]
