# Generated by Django 4.0.4 on 2022-04-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_member_phone_alter_member_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(default='Bill investment paper. Where near memory if traditional.\nResource particularly religious season.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='+398-281-2603x6679', max_length=20, verbose_name='Phone'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='My name')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
            ],
        ),
    ]
