# Generated by Django 4.0.4 on 2022-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_member_description_alter_member_phone_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(default='Perhaps require fact name just must whose. Management thousand already week. To organization magazine face result.\nResearch manage always father total.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='+081-872-3600x029', max_length=20, verbose_name='Phone'),
        ),
    ]
